const app=document.querySelector('#app');
const logo=`<svg class="logo" viewBox="0 0 64 100" fill="currentColor" aria-label="Astrainterview 领带标志"><path d="M13 12C13 0 51 0 51 12L47 21C40 14 24 14 17 21ZM10 14 23 33 15 39 3 25ZM54 14 41 33 49 39 61 25ZM25 35H39L47 41 40 53H24L17 41ZM24 56H40L51 86 32 100 13 86Z"/></svg>`;
const paths={home:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',phone:'<path d="M7 3H4c-3 10 7 20 17 17v-4l-5-2-2 3c-4-2-6-4-7-7l3-2Z"/>',chart:'<path d="m12 2 9 6-3 11H6L3 8Z"/><path d="m12 7 5 4-2 5H9l-2-5Z"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-3a8 8 0 0 1 16 0v3"/>',file:'<path d="M5 3h9l5 5v13H5Z M14 3v6h5 M8 13h8 M8 17h6"/>',mic:'<rect x="9" y="2" width="6" height="13" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/>'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24">${paths[n]||paths.file}</svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user=sessionStorage.getItem('astra-user')||'',register=false,level='应届',selection={},mode='text',messages=[],resumes=[],history=[],recognition=null;
const questions=['你好，欢迎来到 Astrainterview。我是你的 AI 面试官。请用 1–2 分钟介绍一下自己，以及你最有代表性的项目。','在这个项目中，你遇到的最大技术挑战是什么？请说明你的解决过程。','为什么选择这个方案？与其他方案相比，你做了哪些权衡？','如果业务规模增长十倍，你会如何改进这个系统？','回顾这段经历，你会用哪些具体指标衡量项目的结果？'];
const config={'应届':[['HR面','综合模拟'],['校招HR面'],['八股基础'],['轻松'],['友好引导']],'低级':[['技术一面','HR面'],['创业公司CTO面'],['项目深挖','行为面试'],['标准'],['正常克制','友好引导']],'中级':[['技术二面','综合模拟','HR面'],['互联网大厂','外企工程经理面'],['系统设计','项目深挖','行为面试','压力面试'],['标准','严格'],['正常克制','犀利追问']],'高级':[['技术二面','综合模拟'],['互联网大厂','创业公司CTO面','外企工程经理面'],['系统设计','项目深挖','压力面试'],['严格'],['犀利追问','沉默压迫']]};
const categories=['面试类型','公司场景','练习重点','面试强度','面试官风格'];
const demo=[{name:'前端开发工程师',type:'技术一面',date:'2026.09.18 · 14:30',score:86},{name:'全栈开发工程师',type:'综合模拟',date:'2026.09.16 · 10:00',score:79}];
const brand=`<div class="brand">${logo}<div>Astrainterview<small>PREPARE. PRACTICE. PROGRESS.</small></div></div>`;
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',3200)}
function go(page){location.hash=page}
function title(en,zh,desc=''){return `<div class="eyebrow">${en}</div><div class="heading"><div><h1>${zh}</h1><p>${desc}</p></div><span class="date">${new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'})}</span></div>`}
function shell(content,page){const active=['resume','history','analysis','report'].includes(page)?'me':page==='custom'||page==='interview'?'phone':page;return `<main class="main"><header class="topbar"><div class="header-brand">${brand}</div><span>Astrainterview <span style="margin:0 13px">/</span> <b>${{home:'面试空间',phone:'电话面试',portrait:'能力画像',me:'我的',custom:'自主难度设置',resume:'我的简历',history:'我的历史',analysis:'分析报告',report:'历史报告',interview:'正在面试'}[page]||'面试空间'}</b></span><div class="top-actions"><span><i class="status-dot"></i>专注于你的下一次成长</span><button data-action="logout">退出登录 ↗</button></div></header><section class="content">${content}<footer class="footer"><span>© 2026 ASTRAINTERVIEW · 为每一次机会，做好准备</span><span>前端交互演示 · 报告为示例数据</span></footer></section></main>`}
function rows(items){return `<div class="recent">${items.map((h,i)=>`<button class="row" data-action="report" data-source="${items===history?'history':'demo'}" data-id="${i}"><span class="card-icon">${icon('phone')}</span><div class="grow"><strong>${esc(h.name)}</strong><small>${esc(h.date)}</small></div><span class="tag">${h.type}</span><span class="score">${h.score??'—'} <small>/ 100</small></span><span style="color:#a3ad97;margin-left:15px">↗</span></button>`).join('')}</div>`}
function home(){return title('YOUR PERSONAL INTERVIEW STUDIO','每一次准备，都更接近理想。','欢迎回到面试空间。今天，也为下一个机会积蓄底气。')+`<section class="hero"><div class="hero-copy"><span class="pill"><i class="status-dot"></i> AI POWERED INTERVIEW</span><h2>下一场面试，从这里开始。</h2><p>真实的面试场景，有深度的对话。<br>让每一次练习，都成为看得见的进步。</p><a class="primary" href="#phone">开始电话面试 <span>↗</span></a></div><div class="hero-art"><div class="orbit two"></div><div class="orbit"></div><div class="orbit three"></div>${logo}<span class="floating one">✧ 专属面试官已就绪</span><span class="floating two">▥ 让实力，自信表达</span></div><div class="watermark">面试空间</div></section><div class="stats">${[['累计练习','12','次','持续积累'],['平均得分','82.5','分','↗ 6.2'],['累计练习时长','186','分钟','专注投入'],['本周练习','3','次','目标 5 次']].map(s=>`<div class="stat"><div class="stat-label">${s[0]}<em>${s[3]}</em></div><strong>${s[1]}<small>${s[2]}</small></strong></div>`).join('')}</div><div class="section-title"><h2>为成长，找到方向</h2><span>EXPLORE YOUR POTENTIAL</span></div><div class="cards"><a class="card clickable" href="#portrait"><div class="card-icon">${icon('chart')}</div><div class="mini-bars">${[20,29,25,36,42].map(h=>`<i style="height:${h}px"></i>`).join('')}</div><h3>能力画像</h3><p>看见你的优势，也看见下一步的成长空间。</p><div class="card-link">探索我的能力 <span>↗</span></div></a><a class="card clickable" href="#me"><div class="card-icon">${icon('user')}</div><h3>我的</h3><p>管理你的简历，回顾每一场有价值的练习。</p><div class="card-link">进入个人中心 <span>↗</span></div></a></div><div class="section-title"><h2>最近的练习 <span style="margin-left:12px">示例记录</span></h2><a href="#history" style="font-size:11px;color:#8d9681">查看全部 ↗</a></div>${rows(demo)}`}
function auth(){return `<div class="auth"><section class="auth-art">${brand}<div class="hero-art"><div class="orbit two"></div><div class="orbit"></div>${logo}</div><div><div class="eyebrow">THE NEXT CHAPTER STARTS HERE</div><h1>准备充分，<br>自信发生。</h1><p>你的专属 AI 面试空间</p></div><small style="color:#87917c">ASTRAINTERVIEW © 2026</small></section><section class="auth-form"><div class="form-wrap">${brand}<h2 style="margin-top:45px">${register?'开启你的成长旅程':'欢迎回来'}</h2><p>为每一次机会，做好准备。</p><div class="tabs"><button data-action="login-tab" class="${!register?'active':''}">登录</button><button data-action="register-tab" class="${register?'active':''}">注册</button></div><form id="auth-form"><label for="student">学号</label><input id="student" name="student" placeholder="输入学号" autocomplete="username" required maxlength="30"><label for="password">密码</label><input id="password" name="password" type="password" placeholder="输入密码" autocomplete="${register?'new-password':'current-password'}" minlength="6" required>${register?'<label for="confirm">确认密码</label><input id="confirm" name="confirm" type="password" placeholder="确认密码" minlength="6" required autocomplete="new-password">':''}<div class="error" id="auth-error" role="alert"></div><button class="primary dark" type="submit">${register?'创建并进入面试空间':'进入面试空间'} ↗</button></form><p style="font-size:11px;text-align:center;margin-top:22px">交互演示：任意学号与 6 位以上密码即可进入。<br>请勿输入真实密码，本原型不提供身份认证。</p></div></section></div>`}
function phone(){return title('MAKE YOUR NEXT MOVE','选择你的面试节奏','从轻松热身到深度挑战，找到适合当下的练习方式。')+`<div class="cards" style="margin-top:35px"><div class="card difficulty" tabindex="0"><span class="eyebrow">01 / GUIDED PRACTICE</span><h2>默认难度设置</h2><p>选择一个起点，让面试官带你进入状态。<br>悬停或点击下方区域选择难度。</p><button class="ghost" data-action="expand">选择练习难度 ↓</button><div class="options">${['简单','中等','困难'].map(x=>`<button class="node" data-action="start" data-value="${x}">${x} ↗</button>`).join('')}</div></div><a class="card difficulty heavy clickable" href="#custom"><span class="eyebrow">02 / BEYOND YOUR COMFORT ZONE</span><h2>自主难度设置 ↗</h2><p>定义规则，直面挑战。<br>定制经验等级、场景与面试官风格。</p><span class="pill" style="margin-top:20px">进入深度挑战 →</span></a></div>`}
function custom(){return `<button class="back" data-action="back" data-value="phone">← 返回难度选择</button>`+title('DESIGN YOUR CHALLENGE','构建你的专属面试','从经验层级出发，沿着能力网络设置五个维度。每个维度选择一项。')+`<div class="network"><div class="levels">${Object.keys(config).map(x=>`<button class="node ${level===x?'selected':''}" data-action="level" data-value="${x}">${x}</button>`).join('')}</div><div class="branches">${categories.map((cat,i)=>`<section class="branch"><h3>${cat}</h3>${config[level][i].map(v=>`<button class="node ${selection[i]===v?'selected':''}" data-action="select" data-id="${i}" data-value="${v}">${v}</button>`).join('')}</section>`).join('')}</div><div class="launch">${Object.keys(selection).length===5?'<button class="primary dark" data-action="start" data-value="自主配置">开始面试 ↗</button>':`<p>已选择 ${Object.keys(selection).length} / 5 个维度，完成后开启面试。</p>`}</div></div>`}
const skills=['技术准确性','技术深度','表达清晰度','业务理解','权衡决策','风险意识','结果量化','岗位匹配度'];
function meters(){return skills.map((s,i)=>`<div class="meter">${s}<span>${[88,79,91,82,76,74,80,90][i]}</span><div class="track"><i style="width:${[88,79,91,82,76,74,80,90][i]}%"></i></div></div>`).join('')}
function portrait(){return title('A CLEARER PICTURE OF YOU','让成长，有迹可循。','在每一次对话中，发现你的能力轮廓。')+`<div class="report-note">以下为界面效果示例，尚未接入真实面试分析。</div><div class="grid3"><div class="card"><h3>平均得分</h3><div class="big-score">82.5 <small>/ 100</small></div><span class="tag">较上周 +6.2 分</span></div><div class="card" style="grid-column:span 2"><h3>基本信息</h3><div class="plan">有效样本 <strong style="float:right">12 场面试</strong></div><div class="plan">稳定优势 <strong style="float:right">表达清晰 · 岗位匹配</strong></div><div class="plan">优先提升 <strong style="float:right">风险意识 · 权衡决策</strong></div></div></div><div class="report-grid"><div class="card"><h3>能力矩阵</h3>${meters()}</div><div class="card"><h3>成长趋势</h3><p>最近 6 次练习 · 综合评分</p><svg class="chart" viewBox="0 0 430 170" role="img" aria-label="示例得分从65分逐步提升到86分"><path d="M20 30H410M20 80H410M20 130H410" stroke="#e1e5d9" fill="none"/><path d="M25 130 100 106 175 112 250 64 325 77 405 35V155H25Z" fill="#e8eddf"/><path d="M25 130 100 106 175 112 250 64 325 77 405 35" stroke="#8b9e72" stroke-width="3" fill="none"/><text x="25" y="169" fill="#929a87" font-size="10">第 1 次</text><text x="367" y="169" fill="#929a87" font-size="10">第 6 次</text></svg><h3>本周提升计划</h3><div class="plan">01 · 完成 2 次系统设计专项练习</div><div class="plan">02 · 用 STAR 结构重述一个项目</div><div class="plan">03 · 为方案补充风险与备选路径</div></div><div class="card"><h3>最近判断依据</h3><p>在示例「缓存方案设计」回答中，能够清晰描述技术路径，但对缓存失效和容量边界的讨论不足。</p><a class="card-link" href="#report">查看逐题复盘 ↗</a></div></div>`}
function me(){return title('YOUR PERSONAL ARCHIVE','我的，每一步积累。','简历是起点，练习是过程，成长是你的答案。')+`<div class="cards" style="margin-top:30px">${[['resume','我的简历','file','上传与阅读 PDF 简历，探索简历分析报告。'],['history','我的历史','phone','回顾面试记录，找到下一次突破的方向。']].map(([id,h,ic,p])=>`<a class="card clickable" href="#${id}"><div class="card-icon">${icon(ic)}</div><h2>${h}</h2><p>${p}</p><span class="card-link">进入查看 ↗</span></a>`).join('')}</div>`}
function resume(){return title('YOUR STORY, WELL PRESENTED','我的简历','整理经历，让每一份潜力被看见。')+`<div class="upload">${icon('file')}<h3>上传你的 PDF 简历</h3><p>仅在当前浏览器会话内预览，不上传文件。支持 PDF，最大 10 MB。</p><input type="file" id="pdf-upload" accept="application/pdf,.pdf" aria-label="上传 PDF 简历"></div>${resumes.length?resumes.map((r,i)=>`<div class="card" style="margin-bottom:20px"><details><summary>${esc(r.name)} <span style="color:#9aa28d">· ${r.date} · 点击展开</span></summary><div class="scroll-paper resume-paper"><div class="resume-frame"><iframe src="${r.url}#view=Fit&toolbar=0&navpanes=0" title="${esc(r.name)} 简历预览" loading="lazy"></iframe></div></div><div class="resume-preview-tools"><span>自动适应预览框</span><a href="${r.url}#view=Fit" target="_blank" rel="noopener">在新窗口查看 ↗</a></div><a class="primary dark" style="margin-top:20px" href="#analysis">简历分析 · 查看示例报告 ↗</a></details></div>`).join(''):'<div class="empty">还没有简历记录，上传第一份简历开始吧。</div>'}`}
function analysis(){return title('RESUME INSIGHTS','简历分析报告','从经历到机会，梳理你的下一步。')+`<div class="report-note">演示报告：当前未解析 PDF 内容，以下建议并非针对已上传的简历。</div><div class="report-grid">${[['岗位匹配结果','前端开发工程师 · 示例匹配度 88%','项目经验和技术栈与岗位要求具有较高关联。'],['推荐就业方向（需确认）','前端开发 / 全栈开发','请结合个人意愿、实际经历与目标岗位确认。'],['结构化解析','教育经历 → 技术技能 → 项目经历','建议采用清晰的时间线，统一技术栈与项目职责的描述方式。'],['简历亮点与风险','亮点：项目链路完整','风险：成果量化不足，个人贡献与团队工作边界不够清晰。'],['高概率面试题','你为什么选择当前的技术方案？','如何定位性能瓶颈？如何证明优化带来了实际效果？'],['简历优化建议','用数据表达你的影响','将“优化页面性能”改为包含基线、方案、结果和测量方式的具体描述。']].map(([h,s,p])=>`<div class="card"><h3>${h}</h3><h2 style="font-size:17px">${s}</h2><p>${p}</p></div>`).join('')}<div class="card"><h3>推荐面试配置</h3><p>面试类型：技术一面<br>面试难度：标准<br>练习重点：项目深挖</p><button class="primary dark" data-action="recommend">生成本场面试配置 ↗</button></div></div>`}
function report(){return title('REFLECT. REFINE. REPEAT.','历史报告','每一个回答，都是下一次进步的起点。')+`<div class="report-note">${sessionStorage.getItem('astra-report-new')==='yes'?'当前练习尚未接入评分服务。以下能力分数及评价为示例；问答复盘为本次实际输入。':'示例报告：能力评分、评价与问答仅用于展示页面效果。'}</div><div class="report-grid"><div class="card"><h3>核心能力模型</h3>${meters()}</div><div><div class="card"><h3>面试官综合评价</h3><p>表达条理清晰，能够完整说明项目背景及技术实现。建议在技术选型时增加对替代方案的比较，并主动说明风险边界。</p></div><div class="card" style="margin-top:20px"><h3>报告结论与训练建议</h3><div class="plan">保持：清晰的回答结构与问题拆解。</div><div class="plan">提升：决策依据、异常路径与量化成果。</div><p>下一次训练建议聚焦「项目深挖」。</p><a class="primary dark" href="#custom">安排下一次练习 ↗</a></div></div><div class="card" style="grid-column:1/-1"><h3>逐题问答复盘</h3>${(sessionStorage.getItem('astra-report-new')==='yes'?messages:[{role:'ai',text:questions[1]},{role:'self',text:'我负责页面性能优化，通过拆分资源和延迟加载降低首屏开销。'}]).map((m,i)=>`<details ${i===0?'open':''}><summary>${m.role==='ai'?'面试官提问':'我的回答'}</summary><p>${esc(m.text)}</p></details>`).join('')}</div></div>`}
function interview(){return `<div class="heading" style="margin-bottom:23px"><div><div class="eyebrow">A CONVERSATION FOR GROWTH</div><h2>专注此刻，自信表达。</h2></div><button class="ghost" data-action="finish">结束面试 ↗</button></div><div class="chat"><div class="chat-head"><span><i class="status-dot"></i>Astra 面试官 <small style="color:#9aa18f"> / ${esc(sessionStorage.getItem('astra-difficulty')||'标准')} · 演示对话</small></span><button class="ghost" data-action="mode">${mode==='text'?'转语音 ♩':'转聊天框 ▤'}</button></div>${mode==='text'?`<div class="messages" id="messages">${messages.map(m=>`<div class="message ${m.role==='self'?'self':''}"><div class="avatar">${m.role==='ai'?logo:'我'}</div><div class="bubble">${esc(m.text)}</div></div>`).join('')}</div><form class="compose" id="chat-form"><input name="message" placeholder="输入你的回答，让面试官了解你的思考…" required autocomplete="off" aria-label="面试回答"><button class="primary dark" type="submit">发送 ↑</button></form>`:`<div class="voice">${logo}<h2>Astra 面试官</h2><p>${esc(messages.filter(m=>m.role==='ai').at(-1)?.text||questions[0])}</p><button class="mic" data-action="listen" aria-label="开始语音识别">${icon('mic')}</button><p id="voice-status">点击麦克风开始语音输入<br>需浏览器支持并授权麦克风</p></div>`}</div>`}
function render(){if(recognition){recognition.abort();recognition=null}const page=location.hash.slice(1)||'login';if(page==='login'||!user){app.innerHTML=auth();return}const screens={home,phone,custom,portrait,me,resume,analysis,report,interview,history:()=>title('EVERY PRACTICE COUNTS','我的历史','回顾每一次对话，收藏每一点进步。')+`<div class="section-title"><h2>本次会话记录</h2></div>${history.length?rows(history):'<div class="empty">尚未完成面试，开始一场练习吧。</div>'}<div class="section-title"><h2>示例记录</h2></div>${rows(demo)}`};app.innerHTML=shell((screens[page]||home)(),page);const el=document.querySelector('#messages');if(el)el.scrollTop=el.scrollHeight}
function answer(text){messages.push({role:'self',text});const n=messages.filter(m=>m.role==='self').length;messages.push({role:'ai',text:questions[n]||'感谢你的回答。本轮演示问题已完成，你可以结束面试并查看问答记录。'});render()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,v=b.dataset.value;if(a==='logout'){user='';sessionStorage.removeItem('astra-user');go('login')}if(a==='login-tab'||a==='register-tab'){register=a==='register-tab';render()}if(a==='back')go(v);if(a==='expand')b.nextElementSibling.style.display='flex';if(a==='level'){level=v;selection={};render()}if(a==='select'){selection[b.dataset.id]=v;render()}if(a==='start'){sessionStorage.setItem('astra-difficulty',v==='自主配置'?`${level} · ${Object.values(selection).join(' / ')}`:v);messages=[{role:'ai',text:questions[0]}];mode='text';go('interview')}if(a==='mode'){mode=mode==='text'?'voice':'text';render()}if(a==='finish'){history.unshift({name:'面试练习（未评分）',date:new Date().toLocaleString('zh-CN'),type:'本次练习',score:null,messages:messages.map(m=>({...m}))});sessionStorage.setItem('astra-report-new','yes');go('report')}if(a==='report'){if(b.dataset.source==='history')messages=history[Number(b.dataset.id)].messages.map(m=>({...m}));sessionStorage.setItem('astra-report-new',b.dataset.source==='history'?'yes':'no');go('report')}if(a==='recommend'){level='低级';selection={0:'技术一面',1:'创业公司CTO面',2:'项目深挖',3:'标准',4:'正常克制'};go('custom')}});
document.addEventListener('submit',e=>{if(e.target.id==='auth-form'){e.preventDefault();const data=new FormData(e.target);if(register&&data.get('password')!==data.get('confirm')){document.querySelector('#auth-error').textContent='两次输入的密码不一致，请重新确认。';return}user=data.get('student').trim();if(!user){document.querySelector('#auth-error').textContent='请输入有效学号。';return}sessionStorage.setItem('astra-user',user);go('home');render()}if(e.target.id==='chat-form'){e.preventDefault();const text=new FormData(e.target).get('message').trim();if(text)answer(text)}});
document.addEventListener('change',e=>{if(e.target.id==='pdf-upload'){const file=e.target.files[0];if(!file)return;if(!file.name.toLowerCase().endsWith('.pdf')||file.size>10*1024*1024){toast('请选择不超过 10 MB 的 PDF 文件。');e.target.value='';return}resumes.unshift({name:file.name,date:new Date().toLocaleDateString('zh-CN'),url:URL.createObjectURL(file)});render();toast('简历已载入，点击记录展开预览。')}});
window.addEventListener('hashchange',render);render();




